package me.tomassetti.bytecode.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class ConstantPoolClass_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_9hh82y_a(editorContext, node);
  }
  private EditorCell createCollection_9hh82y_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_9hh82y_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createComponent_9hh82y_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_9hh82y_b0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_9hh82y_c0(editorContext, node));
    return editorCell;
  }
  private EditorCell createComponent_9hh82y_a0(EditorContext editorContext, SNode node) {
    EditorCell editorCell = editorContext.getCellFactory().createEditorComponentCell(node, "me.tomassetti.bytecode.editor.ConstantPoolElementIndex");
    return editorCell;
  }
  private EditorCell createConstant_9hh82y_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "CP Class");
    editorCell.setCellId("Constant_9hh82y_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_9hh82y_c0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new ConstantPoolClass_Editor.nameIndexSingleRoleHandler_9hh82y_c0(node, MetaAdapterFactory.getContainmentLink(0x1392eb99581d482bL, 0xaa2819e40eaffbe2L, 0x1695a3631a43d9beL, 0x1695a3631a47ef15L, "nameIndex"), editorContext);
    return provider.createCell();
  }
  private class nameIndexSingleRoleHandler_9hh82y_c0 extends SingleRoleCellProvider {
    public nameIndexSingleRoleHandler_9hh82y_c0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("nameIndex");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_nameIndex");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no nameIndex>";
    }
  }
}
