package me.tomassetti.bytecode.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class SignatureAttributeInfoData_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_eizyoo_a(editorContext, node);
  }
  private EditorCell createCollection_eizyoo_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_eizyoo_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_eizyoo_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_eizyoo_b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_eizyoo_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "signature");
    editorCell.setCellId("Constant_eizyoo_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_eizyoo_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new SignatureAttributeInfoData_Editor.signatureSingleRoleHandler_eizyoo_b0(node, MetaAdapterFactory.getContainmentLink(0x1392eb99581d482bL, 0xaa2819e40eaffbe2L, 0xd2b536b37e91620L, 0xd2b536b37e91621L, "signature"), editorContext);
    return provider.createCell();
  }
  private class signatureSingleRoleHandler_eizyoo_b0 extends SingleRoleCellProvider {
    public signatureSingleRoleHandler_eizyoo_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("signature");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_signature");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no signature>";
    }
  }
}
