package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class AttributeInfoData_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.AttributeInfoData";
  }

  public abstract void virtual_serialize_7146026317576300452(SNode __thisNode__, MyDataOStream mds);
  public abstract long virtual_length_8111651899336742631(SNode __thisNode__);
}
