package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.Map;
import java.math.BigInteger;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.List;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ClassFileLoader_Behavior {
  public static String call_asHexadecimal_1627386486401919697(SNode __thisNode__, byte b) {
    return ClassFileLoader__BehaviorDescriptor.asHexadecimal_id1qlCQcqguFh(__thisNode__, b);
  }
  public static long call_toInteger_1627386486401968272(SNode __thisNode__, byte[] b) {
    return ClassFileLoader__BehaviorDescriptor.toInteger_id1qlCQcqgEyg(__thisNode__, b);
  }
  public static long call_pow_1627386486401985559(SNode __thisNode__, int base, int exp) {
    return ClassFileLoader__BehaviorDescriptor.pow_id1qlCQcqgIKn(__thisNode__, base, exp);
  }
  public static long call_toInteger_1627386486401969489(SNode __thisNode__, byte[] b, int index) {
    return ClassFileLoader__BehaviorDescriptor.toInteger_id1qlCQcqgEPh(__thisNode__, b, index);
  }
  public static void call_load_1627386486401890679(SNode __thisNode__) {
    ClassFileLoader__BehaviorDescriptor.load_id1qlCQcqgn_R(__thisNode__);
  }
  public static SNode call_loadClassAccessFlags_1627386486403017320(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.loadClassAccessFlags_id1qlCQcqkEDC(__thisNode__, mds);
  }
  public static SNode call_loadMethodAccessFlags_1627386486403025802(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.loadMethodAccessFlags_id1qlCQcqkGIa(__thisNode__, mds);
  }
  public static SNode call_loadAccessFlags_1627386486402817284(SNode __thisNode__, MyDataIStream mds, Map<Integer, String> mapping) {
    return ClassFileLoader__BehaviorDescriptor.loadAccessFlags_id1qlCQcqjTO4(__thisNode__, mds, mapping);
  }
  public static SNode call_loadMethodInfo_1627386486402772426(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.loadMethodInfo_id1qlCQcqjIRa(__thisNode__, mds);
  }
  public static SNode call_toUtf8Reference_948943866455876226(SNode __thisNode__, long index) {
    return ClassFileLoader__BehaviorDescriptor.toUtf8Reference_idOFkQGRSQa2(__thisNode__, index);
  }
  public static SNode call_toClassReference_5213767832181379345(SNode __thisNode__, long index) {
    return ClassFileLoader__BehaviorDescriptor.toClassReference_id4xr1zwUxT4h(__thisNode__, index);
  }
  public static SNode call_toNameAndTypeReference_4103136884613196905(SNode __thisNode__, long index) {
    return ClassFileLoader__BehaviorDescriptor.toNameAndTypeReference_id3zLhk7ob2LD(__thisNode__, index);
  }
  public static SNode call_loadFieldInfo_948943866455813894(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.loadFieldInfo_idOFkQGRSAW6(__thisNode__, mds);
  }
  public static SNode call_loadInterfaceInfo_5213767832182121462(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.loadInterfaceInfo_id4xr1zwU$IfQ(__thisNode__, mds);
  }
  public static SNode call_getConstantPoolElement_486623176541192300(SNode __thisNode__, SNode index) {
    return ClassFileLoader__BehaviorDescriptor.getConstantPoolElement_idr0PjdDds1G(__thisNode__, index);
  }
  public static SNode call_loadAttributeInfo_1627386486402964245(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.loadAttributeInfo_id1qlCQcqktGl(__thisNode__, mds);
  }
  public static SNode call_readSignature_948943866456273354(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.readSignature_idOFkQGRUn7a(__thisNode__, mds);
  }
  public static SNode call_readCode_486623176541363249(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.readCode_idr0PjdDe5KL(__thisNode__, mds);
  }
  public static SNode call_readExceptionTableElement_948943866458328803(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.readExceptionTableElement_idOFkQGS2cVz(__thisNode__, mds);
  }
  public static BigInteger call_parse_948943866456486322(SNode __thisNode__, MyDataIStream mds, BigInteger i, SAbstractConcept concept, List<SNode> instructions) {
    return ClassFileLoader__BehaviorDescriptor.parse_idOFkQGRVb6M(__thisNode__, mds, i, concept, instructions);
  }
  public static List<SNode> call_readCodeArray_486623176541932422(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.readCodeArray_idr0PjdDggI6(__thisNode__, mds);
  }
  public static SNode call_readArray_486623176541939996(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.readArray_idr0PjdDgi$s(__thisNode__, mds);
  }
  public static SNode call_readArray_1627386486403097656(SNode __thisNode__, MyDataIStream mds) {
    return ClassFileLoader__BehaviorDescriptor.readArray_id1qlCQcqkYgS(__thisNode__, mds);
  }
}
