package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import me.tomassetti.bytecode.execution.behavior.IClassProducer_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ClassFile_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IClassProducer_BehaviorDescriptor {
  public String virtual_getPresentation_1213877396640(SNode __thisNode__) {
    return null;
  }
  public String virtual_qualifiedClassName_5213767832181122356(SNode __thisNode__) {
    return null;
  }
  public String virtual_simpleClassName_5213767832182485080(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.ClassFile";
  }

}
