package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class CodeAttributeInfoData_BehaviorDescriptor extends AttributeInfoData_BehaviorDescriptor {
  public long virtual_length_8111651899336742631(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Long.TYPE);
  }
  public void virtual_serialize_7146026317576300452(SNode __thisNode__, MyDataOStream mds) {
  }

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.CodeAttributeInfoData";
  }

}
