package me.tomassetti.bytecode.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ConstantPoolElement_Behavior {
}
