package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class ConstantPoolElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public String virtual_getFqName_1213877404258(SNode __thisNode__) {
    return null;
  }
  public int virtual_length_7315755912296132073(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.ConstantPoolElement";
  }

  public abstract ConstantPoolElementType virtual_tag_1627386486402044802(SNode __thisNode__);
  public abstract void virtual_serializeInfo_7146026317575600640(SNode __thisNode__, MyDataOStream mds);
}
