package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class ConstantPoolElement_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.ConstantPoolElement";
  }

  public abstract ConstantPoolElementType virtual_tag_1627386486402044802(SNode __thisNode__);
  public abstract void virtual_serializeInfo_7146026317575600640(SNode __thisNode__, MyDataOStream mds);
}
