package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ConstantPoolLong_Behavior {
  public static boolean call_isDoubleElement_7489115193973946772(SNode __thisNode__) {
    return ConstantPoolLong__BehaviorDescriptor.isDoubleElement_id6vIFDs2N3Ak(__thisNode__);
  }
}
