package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class ConstantPoolElement_Behavior {
  public static boolean call_isDoubleElement_7489115193973946538(SNode __thisNode__) {
    return ConstantPoolElement__BehaviorDescriptor.isDoubleElement_id6vIFDs2N3yE(__thisNode__);
  }
  public static long call_index_948943866455367871(SNode __thisNode__) {
    return ConstantPoolElement__BehaviorDescriptor.index_idOFkQGRQU2Z(__thisNode__);
  }
  public static void call_serialize_7146026317575597270(SNode __thisNode__, MyDataOStream mds) {
    ConstantPoolElement__BehaviorDescriptor.serialize_id6cFMhcmFUNm(__thisNode__, mds);
  }
}
