package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ConstantPoolFieldref_BehaviorDescriptor extends ConstantPoolElement_BehaviorDescriptor {
  public ConstantPoolElementType virtual_tag_1627386486402044802(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.ConstantPoolFieldref";
  }

}
