package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ConstantPoolLong_BehaviorDescriptor extends ConstantPoolElement_BehaviorDescriptor {
  public int virtual_length_7315755912296132073(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }
  public void virtual_serializeInfo_7146026317575600640(SNode __thisNode__, MyDataOStream mds) {
  }
  public ConstantPoolElementType virtual_tag_1627386486402044802(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.ConstantPoolLong";
  }

}
