package me.tomassetti.bytecode.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class If_icmpeq_BehaviorDescriptor extends If_icmpcond_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.If_icmpeq";
  }

}
