package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.DefaultValuesHolder;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class Instruction_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public int virtual_length_1530027263845189390(SNode __thisNode__) {
    return DefaultValuesHolder.defaultValue(Integer.TYPE);
  }
  public void virtual_serialize_8111651899336990316(SNode __thisNode__, MyDataOStream mds) {
  }

  @Override
  public String getConceptFqName() {
    return "me.tomassetti.bytecode.structure.Instruction";
  }

}
