package me.tomassetti.bytecode.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Unsigned2Bytes_Behavior {
  public static long call_toLong_1627386486402647188(SNode __thisNode__) {
    return Unsigned2Bytes__BehaviorDescriptor.toLong_id1qlCQcqjgik(__thisNode__);
  }
}
